
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision if down_revision else None}
Create Date: ${create_date}

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "024210547839"
down_revision = 'beb8ce283f38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('default', sa.Boolean(), nullable=False))
    op.alter_column('widgets', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('widgets', 'default')
    # ### end Alembic commands ###
