
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision if down_revision else None}
Create Date: ${create_date}

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09b13f11a942"
down_revision = 'a6f1565b1b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('class_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'class_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
