
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision if down_revision else None}
Create Date: ${create_date}

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "beb8ce283f38"
down_revision = '09b13f11a942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'class_name')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
