
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision if down_revision else None}
Create Date: ${create_date}

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c995adca839d"
down_revision = 'c4a2b3d5e6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
